name: Auto release

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          keep_history: true
          allow_empty_commit: false
          build_dir: dist
          commit_message: "Auto publish from commit ${{ steps.short-sha.outputs.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
